vg_name = "ubuntu-vg"
lv_name = "ubuntu-lv"
snap_prefix = "snap_id"     # Tiền tố tên snapshot
max_snapshots = 2            # Giữ tối đa 2 bản (mỗi snapshot 3GB)
base_path = "/mnt/lvm_public" # Thư mục để mount và chia sẻ Rsync
sudo_password = "1234@abcd" # Thay đổi thành mật khẩu sudo để tự động cấp quyền
share_subdir = "/home/abc/nhat/consensus-chain/mtn-simple-2025/cmd/simple_chain/sample/simple/data-write/data"   # Thư mục con cần chia sẻ dưới mỗi snapshot
