vg_name = "ubuntu-vg"
lv_name = "ubuntu-lv"
snap_prefix = "snap_id"     # Tiền tố tên snapshot
max_snapshots = 2            # Giữ tối đa 2 bản mới nhất
base_path = "/mnt/lvm_public" # Thư mục để mount snapshot
sudo_password = "1234@abcd"  # Mật khẩu sudo để tự động cấp quyền
serve_port = 8600            # Port cho HTTP download server
